name: deploy
on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV
        required: true
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: "Install & build"
        run: |
          npm i
          npm run build
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v5.0.0
        with:
          ARGS: -avzr --delete
          SOURCE: "./dist/"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }}
          TARGET: /var/www/grocery-app/
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
